#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t serial_baudrate;
    bool clear_display;
    bool output_power;
    bool pmic_button;
    bool internal_imu;
    bool internal_rtc;
    bool internal_mic;
    bool internal_spk;
    bool external_imu;
    bool external_rtc;
    bool disable_rtc_irq;
    uint8_t led_brightness;
    uint16_t external_speaker_value;
    uint16_t external_display_value;
} m5u_config_t;

bool m5u_begin(void);
bool m5u_begin_with_config(const m5u_config_t* config);
void m5u_update(void);
void m5u_delay_ms(uint32_t ms);
uint32_t m5u_millis(void);
uint32_t m5u_micros(void);
uint32_t m5u_get_update_msec(void);
int m5u_get_board(void);
int m5u_get_pin(int name);

int m5u_display_width(void);
int m5u_display_height(void);
void m5u_display_fill_screen(uint16_t color);
void m5u_display_set_cursor(int x, int y);
void m5u_display_set_text_size(int size);
void m5u_display_set_text_color(uint16_t fg, uint16_t bg);
void m5u_display_print(const char* text);
void m5u_display_println(const char* text);
void m5u_display_draw_line(int x0, int y0, int x1, int y1, uint16_t color);
void m5u_display_draw_pixel(int x, int y, uint16_t color);
uint16_t m5u_display_read_pixel(int x, int y);
void m5u_display_draw_fast_hline(int x, int y, int w, uint16_t color);
void m5u_display_draw_fast_vline(int x, int y, int h, uint16_t color);
void m5u_display_draw_rect(int x, int y, int w, int h, uint16_t color);
void m5u_display_fill_rect(int x, int y, int w, int h, uint16_t color);
void m5u_display_fill_rect_alpha(int x, int y, int w, int h, uint8_t alpha, uint16_t color);
void m5u_display_draw_round_rect(int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_fill_round_rect(int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_draw_circle(int x, int y, int r, uint16_t color);
void m5u_display_fill_circle(int x, int y, int r, uint16_t color);
void m5u_display_draw_ellipse(int x, int y, int rx, int ry, uint16_t color);
void m5u_display_fill_ellipse(int x, int y, int rx, int ry, uint16_t color);
void m5u_display_draw_arc(int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_fill_arc(int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_draw_triangle(int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_fill_triangle(int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_progress_bar(int x, int y, int w, int h, uint8_t value);
void m5u_display_set_rotation(int rotation);
int m5u_display_get_rotation(void);
void m5u_display_set_brightness(uint8_t brightness);
uint8_t m5u_display_get_brightness(void);
void m5u_display_set_color_depth(uint8_t depth);
uint8_t m5u_display_get_color_depth(void);
bool m5u_display_is_epd(void);
void m5u_display_set_epd_mode(int mode);
int m5u_display_get_epd_mode(void);
void m5u_display_set_epd_fastest(void);
bool m5u_display_set_resolution(uint16_t logical_width, uint16_t logical_height, float refresh_rate, uint16_t output_width, uint16_t output_height, uint8_t scale_w, uint8_t scale_h, uint32_t pixel_clock);
void m5u_display_start_write(void);
void m5u_display_end_write(void);
void m5u_display_display(void);
bool m5u_display_display_busy(void);
void m5u_display_wait_display(void);
void m5u_display_sleep(void);
void m5u_display_wakeup(void);
void m5u_display_power_save_on(void);
void m5u_display_power_save_off(void);
void m5u_display_power_save(bool enable);
void m5u_display_invert_display(bool invert);
int m5u_display_get_cursor_x(void);
int m5u_display_get_cursor_y(void);
void m5u_display_set_pivot(float x, float y);
float m5u_display_get_pivot_x(void);
float m5u_display_get_pivot_y(void);
int m5u_display_font_height(void);
int m5u_display_font_width(void);
bool m5u_display_set_font(int font);
bool m5u_display_show_font(uint32_t duration_ms);
void m5u_display_unload_font(void);
int m5u_display_font_height_for(int font);
int m5u_display_font_width_for(int font);
uint16_t m5u_display_get_base_color(void);
void m5u_display_set_base_color(uint16_t color);
void m5u_display_set_color(uint16_t color);
void m5u_display_set_rgb_color(uint8_t r, uint8_t g, uint8_t b);
void m5u_display_set_raw_color(uint32_t color);
uint32_t m5u_display_get_raw_color(void);
uint32_t m5u_display_get_palette_count(void);
void m5u_display_set_swap_bytes(bool swap);
bool m5u_display_get_swap_bytes(void);
uint16_t m5u_display_swap565(uint8_t r, uint8_t g, uint8_t b);
uint32_t m5u_display_swap888(uint8_t r, uint8_t g, uint8_t b);
void m5u_display_set_text_wrap(bool wrap_x, bool wrap_y);
void m5u_display_set_text_datum(int datum);
int m5u_display_get_text_datum(void);
void m5u_display_set_text_padding(uint32_t padding_x);
uint32_t m5u_display_get_text_padding(void);
uint8_t m5u_display_get_text_size_x(void);
uint8_t m5u_display_get_text_size_y(void);
int m5u_display_text_length(const char* text);
int m5u_display_text_width(const char* text);
int m5u_display_draw_center_string(const char* text, int x, int y);
int m5u_display_draw_string(const char* text, int x, int y);
int m5u_display_draw_char(uint32_t codepoint, int x, int y);
int m5u_display_draw_number(int32_t value, int x, int y);
int m5u_display_draw_float(float value, uint8_t decimals, int x, int y);
bool m5u_display_draw_bmp(const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_display_draw_jpg(const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_display_draw_png(const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_display_push_image_rgb565(int x, int y, int w, int h, const uint16_t* data, size_t len);
void m5u_display_write_pixel(int x, int y, uint16_t color);
void m5u_display_write_fast_vline(int x, int y, int h, uint16_t color);
void m5u_display_set_addr_window(int x, int y, int w, int h);
void m5u_display_set_window(int xs, int ys, int xe, int ye);
void m5u_display_set_clip_rect(int x, int y, int w, int h);
void m5u_display_get_clip_rect(int* x, int* y, int* w, int* h);
void m5u_display_clear_clip_rect(void);
void m5u_display_scroll(int dx, int dy);
void m5u_display_set_text_scroll(bool enable);
void m5u_display_set_scroll_rect(int x, int y, int w, int h, uint16_t color);
void m5u_display_get_scroll_rect(int* x, int* y, int* w, int* h);
void m5u_display_clear_scroll_rect(void);
uint16_t m5u_display_color888(uint8_t r, uint8_t g, uint8_t b);

typedef void m5u_canvas_t;
m5u_canvas_t* m5u_canvas_create_for_display(void);
m5u_canvas_t* m5u_canvas_create_for_cardputer_display(void);
void m5u_canvas_delete(m5u_canvas_t* canvas);
bool m5u_canvas_create_sprite(m5u_canvas_t* canvas, int w, int h);
void m5u_canvas_delete_sprite(m5u_canvas_t* canvas);
void m5u_canvas_push_sprite(m5u_canvas_t* canvas, int x, int y);
int m5u_canvas_width(m5u_canvas_t* canvas);
int m5u_canvas_height(m5u_canvas_t* canvas);
void m5u_canvas_fill_screen(m5u_canvas_t* canvas, uint16_t color);
void m5u_canvas_set_cursor(m5u_canvas_t* canvas, int x, int y);
void m5u_canvas_set_text_size(m5u_canvas_t* canvas, float size);
void m5u_canvas_set_text_color(m5u_canvas_t* canvas, uint16_t fg, uint16_t bg);
void m5u_canvas_set_text_scroll(m5u_canvas_t* canvas, bool enable);
void m5u_canvas_set_text_datum(m5u_canvas_t* canvas, int datum);
int m5u_canvas_get_text_datum(m5u_canvas_t* canvas);
void m5u_canvas_set_text_padding(m5u_canvas_t* canvas, uint32_t padding_x);
uint32_t m5u_canvas_get_text_padding(m5u_canvas_t* canvas);
uint8_t m5u_canvas_get_text_size_x(m5u_canvas_t* canvas);
uint8_t m5u_canvas_get_text_size_y(m5u_canvas_t* canvas);
uint16_t m5u_canvas_get_base_color(m5u_canvas_t* canvas);
void m5u_canvas_set_base_color(m5u_canvas_t* canvas, uint16_t color);
void m5u_canvas_set_color(m5u_canvas_t* canvas, uint16_t color);
void m5u_canvas_set_rgb_color(m5u_canvas_t* canvas, uint8_t r, uint8_t g, uint8_t b);
void m5u_canvas_set_raw_color(m5u_canvas_t* canvas, uint32_t color);
uint32_t m5u_canvas_get_raw_color(m5u_canvas_t* canvas);
void m5u_canvas_set_swap_bytes(m5u_canvas_t* canvas, bool swap);
bool m5u_canvas_get_swap_bytes(m5u_canvas_t* canvas);
bool m5u_canvas_set_font(m5u_canvas_t* canvas, int font);
int m5u_canvas_font_height(m5u_canvas_t* canvas);
int m5u_canvas_font_width(m5u_canvas_t* canvas);
bool m5u_canvas_show_font(m5u_canvas_t* canvas, uint32_t duration_ms);
void m5u_canvas_unload_font(m5u_canvas_t* canvas);
int m5u_canvas_text_width(m5u_canvas_t* canvas, const char* text);
void m5u_canvas_print(m5u_canvas_t* canvas, const char* text);
void m5u_canvas_println(m5u_canvas_t* canvas, const char* text);
int m5u_canvas_draw_center_string(m5u_canvas_t* canvas, const char* text, int x, int y);
int m5u_canvas_draw_string(m5u_canvas_t* canvas, const char* text, int x, int y);
void m5u_canvas_draw_line(m5u_canvas_t* canvas, int x0, int y0, int x1, int y1, uint16_t color);
void m5u_canvas_draw_rect(m5u_canvas_t* canvas, int x, int y, int w, int h, uint16_t color);
void m5u_canvas_fill_rect(m5u_canvas_t* canvas, int x, int y, int w, int h, uint16_t color);
void m5u_canvas_draw_circle(m5u_canvas_t* canvas, int x, int y, int r, uint16_t color);
void m5u_canvas_fill_circle(m5u_canvas_t* canvas, int x, int y, int r, uint16_t color);
void m5u_canvas_draw_pixel(m5u_canvas_t* canvas, int x, int y, uint16_t color);
uint16_t m5u_canvas_read_pixel(m5u_canvas_t* canvas, int x, int y);
void m5u_canvas_draw_fast_hline(m5u_canvas_t* canvas, int x, int y, int w, uint16_t color);
void m5u_canvas_draw_fast_vline(m5u_canvas_t* canvas, int x, int y, int h, uint16_t color);
void m5u_canvas_draw_round_rect(m5u_canvas_t* canvas, int x, int y, int w, int h, int r, uint16_t color);
void m5u_canvas_fill_round_rect(m5u_canvas_t* canvas, int x, int y, int w, int h, int r, uint16_t color);
void m5u_canvas_draw_ellipse(m5u_canvas_t* canvas, int x, int y, int rx, int ry, uint16_t color);
void m5u_canvas_fill_ellipse(m5u_canvas_t* canvas, int x, int y, int rx, int ry, uint16_t color);
void m5u_canvas_draw_arc(m5u_canvas_t* canvas, int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_canvas_fill_arc(m5u_canvas_t* canvas, int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_canvas_draw_triangle(m5u_canvas_t* canvas, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_canvas_fill_triangle(m5u_canvas_t* canvas, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_canvas_progress_bar(m5u_canvas_t* canvas, int x, int y, int w, int h, uint8_t value);
int m5u_canvas_text_length(m5u_canvas_t* canvas, const char* text);
int m5u_canvas_draw_char(m5u_canvas_t* canvas, uint32_t codepoint, int x, int y);
int m5u_canvas_draw_number(m5u_canvas_t* canvas, int32_t value, int x, int y);
int m5u_canvas_draw_float(m5u_canvas_t* canvas, float value, uint8_t decimals, int x, int y);
bool m5u_canvas_draw_bmp(m5u_canvas_t* canvas, const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_canvas_draw_jpg(m5u_canvas_t* canvas, const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_canvas_draw_png(m5u_canvas_t* canvas, const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_canvas_push_image_rgb565(m5u_canvas_t* canvas, int x, int y, int w, int h, const uint16_t* data, size_t len);
void m5u_canvas_write_pixel(m5u_canvas_t* canvas, int x, int y, uint16_t color);
void m5u_canvas_write_fast_vline(m5u_canvas_t* canvas, int x, int y, int h, uint16_t color);
void m5u_canvas_set_addr_window(m5u_canvas_t* canvas, int x, int y, int w, int h);
void m5u_canvas_set_window(m5u_canvas_t* canvas, int xs, int ys, int xe, int ye);
void m5u_canvas_set_clip_rect(m5u_canvas_t* canvas, int x, int y, int w, int h);
void m5u_canvas_get_clip_rect(m5u_canvas_t* canvas, int* x, int* y, int* w, int* h);
void m5u_canvas_clear_clip_rect(m5u_canvas_t* canvas);
void m5u_canvas_scroll(m5u_canvas_t* canvas, int dx, int dy);
void m5u_canvas_set_scroll_rect(m5u_canvas_t* canvas, int x, int y, int w, int h, uint16_t color);
void m5u_canvas_get_scroll_rect(m5u_canvas_t* canvas, int* x, int* y, int* w, int* h);
void m5u_canvas_clear_scroll_rect(m5u_canvas_t* canvas);

int m5u_display_count(void);
int m5u_display_index_for_kind(int kind);
bool m5u_display_set_primary(int index);
bool m5u_display_set_primary_kind(int kind);
void m5u_display_set_rotation_at(int index, int rotation);
int m5u_display_get_rotation_at(int index);
void m5u_display_set_brightness_at(int index, uint8_t brightness);
uint8_t m5u_display_get_brightness_at(int index);
void m5u_display_set_color_depth_at(int index, uint8_t depth);
uint8_t m5u_display_get_color_depth_at(int index);
bool m5u_display_is_epd_at(int index);
void m5u_display_set_epd_mode_at(int index, int mode);
int m5u_display_get_epd_mode_at(int index);
bool m5u_display_set_resolution_at(int index, uint16_t logical_width, uint16_t logical_height, float refresh_rate, uint16_t output_width, uint16_t output_height, uint8_t scale_w, uint8_t scale_h, uint32_t pixel_clock);
int m5u_display_width_at(int index);
int m5u_display_height_at(int index);
void m5u_display_start_write_at(int index);
void m5u_display_end_write_at(int index);
void m5u_display_display_at(int index);
bool m5u_display_display_busy_at(int index);
void m5u_display_wait_display_at(int index);
void m5u_display_sleep_at(int index);
void m5u_display_wakeup_at(int index);
void m5u_display_power_save_on_at(int index);
void m5u_display_power_save_off_at(int index);
void m5u_display_power_save_at(int index, bool enable);
void m5u_display_invert_display_at(int index, bool invert);
int m5u_display_get_cursor_x_at(int index);
int m5u_display_get_cursor_y_at(int index);
void m5u_display_set_pivot_at(int index, float x, float y);
float m5u_display_get_pivot_x_at(int index);
float m5u_display_get_pivot_y_at(int index);
void m5u_display_clear_at(int index, uint16_t color);
void m5u_display_set_cursor_at(int index, int x, int y);
void m5u_display_set_text_size_at(int index, int size);
void m5u_display_set_text_color_at(int index, uint16_t fg, uint16_t bg);
void m5u_display_set_text_datum_at(int index, int datum);
int m5u_display_get_text_datum_at(int index);
void m5u_display_set_text_padding_at(int index, uint32_t padding_x);
uint32_t m5u_display_get_text_padding_at(int index);
uint8_t m5u_display_get_text_size_x_at(int index);
uint8_t m5u_display_get_text_size_y_at(int index);
int m5u_display_font_height_at(int index);
int m5u_display_font_width_at(int index);
bool m5u_display_set_font_at(int index, int font);
bool m5u_display_show_font_at(int index, uint32_t duration_ms);
void m5u_display_unload_font_at(int index);
uint16_t m5u_display_get_base_color_at(int index);
void m5u_display_set_base_color_at(int index, uint16_t color);
void m5u_display_set_color_at(int index, uint16_t color);
void m5u_display_set_rgb_color_at(int index, uint8_t r, uint8_t g, uint8_t b);
void m5u_display_set_raw_color_at(int index, uint32_t color);
uint32_t m5u_display_get_raw_color_at(int index);
uint32_t m5u_display_get_palette_count_at(int index);
void m5u_display_set_swap_bytes_at(int index, bool swap);
bool m5u_display_get_swap_bytes_at(int index);
uint16_t m5u_display_swap565_at(int index, uint8_t r, uint8_t g, uint8_t b);
uint32_t m5u_display_swap888_at(int index, uint8_t r, uint8_t g, uint8_t b);
void m5u_display_set_text_wrap_at(int index, bool wrap_x, bool wrap_y);
uint16_t m5u_display_color888_at(int index, uint8_t r, uint8_t g, uint8_t b);
int m5u_display_text_length_at(int index, const char* text);
int m5u_display_text_width_at(int index, const char* text);
void m5u_display_print_at(int index, const char* text);
void m5u_display_println_at(int index, const char* text);
int m5u_display_draw_center_string_at(int index, const char* text, int x, int y);
int m5u_display_draw_string_at(int index, const char* text, int x, int y);
int m5u_display_draw_char_at(int index, uint32_t codepoint, int x, int y);
int m5u_display_draw_number_at(int index, int32_t value, int x, int y);
int m5u_display_draw_float_at(int index, float value, uint8_t decimals, int x, int y);
bool m5u_display_draw_bmp_at(int index, const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_display_draw_jpg_at(int index, const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
bool m5u_display_draw_png_at(int index, const uint8_t* data, size_t len, int x, int y, int max_width, int max_height, int off_x, int off_y, float scale_x, float scale_y, int datum);
void m5u_display_draw_line_at(int index, int x0, int y0, int x1, int y1, uint16_t color);
void m5u_display_draw_pixel_at(int index, int x, int y, uint16_t color);
uint16_t m5u_display_read_pixel_at(int index, int x, int y);
void m5u_display_draw_fast_hline_at(int index, int x, int y, int w, uint16_t color);
void m5u_display_draw_fast_vline_at(int index, int x, int y, int h, uint16_t color);
void m5u_display_draw_rect_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_fill_rect_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_fill_rect_alpha_at(int index, int x, int y, int w, int h, uint8_t alpha, uint16_t color);
void m5u_display_draw_round_rect_at(int index, int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_fill_round_rect_at(int index, int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_draw_circle_at(int index, int x, int y, int r, uint16_t color);
void m5u_display_fill_circle_at(int index, int x, int y, int r, uint16_t color);
void m5u_display_draw_ellipse_at(int index, int x, int y, int rx, int ry, uint16_t color);
void m5u_display_fill_ellipse_at(int index, int x, int y, int rx, int ry, uint16_t color);
void m5u_display_draw_arc_at(int index, int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_fill_arc_at(int index, int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_draw_triangle_at(int index, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_fill_triangle_at(int index, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_progress_bar_at(int index, int x, int y, int w, int h, uint8_t value);
bool m5u_display_push_image_rgb565_at(int index, int x, int y, int w, int h, const uint16_t* data, size_t len);
void m5u_display_write_pixel_at(int index, int x, int y, uint16_t color);
void m5u_display_write_fast_vline_at(int index, int x, int y, int h, uint16_t color);
void m5u_display_set_addr_window_at(int index, int x, int y, int w, int h);
void m5u_display_set_window_at(int index, int xs, int ys, int xe, int ye);
void m5u_display_set_clip_rect_at(int index, int x, int y, int w, int h);
void m5u_display_get_clip_rect_at(int index, int* x, int* y, int* w, int* h);
void m5u_display_clear_clip_rect_at(int index);
void m5u_display_scroll_at(int index, int dx, int dy);
void m5u_display_set_text_scroll_at(int index, bool enable);
void m5u_display_set_scroll_rect_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_get_scroll_rect_at(int index, int* x, int* y, int* w, int* h);
void m5u_display_clear_scroll_rect_at(int index);

bool m5u_btn_a_is_pressed(void);
bool m5u_btn_a_was_pressed(void);
bool m5u_btn_a_was_released(void);
bool m5u_btn_b_is_pressed(void);
bool m5u_btn_b_was_pressed(void);
bool m5u_btn_b_was_released(void);
bool m5u_btn_c_is_pressed(void);
bool m5u_btn_c_was_pressed(void);
bool m5u_btn_c_was_released(void);
bool m5u_button_is_pressed(int button);
bool m5u_button_was_pressed(int button);
bool m5u_button_was_released(int button);
bool m5u_button_was_clicked(int button);
bool m5u_button_was_hold(int button);
bool m5u_button_was_single_clicked(int button);
bool m5u_button_was_double_clicked(int button);
bool m5u_button_was_change_pressed(int button);
bool m5u_button_is_holding(int button);
bool m5u_button_is_released(int button);
bool m5u_button_was_released_after_hold(int button);
bool m5u_button_was_release_for(int button, uint32_t ms);
bool m5u_button_pressed_for(int button, uint32_t ms);
bool m5u_button_released_for(int button, uint32_t ms);
bool m5u_button_was_decide_click_count(int button);
int m5u_button_get_click_count(int button);
void m5u_button_set_debounce_thresh(int button, uint32_t msec);
void m5u_button_set_hold_thresh(int button, uint32_t msec);
void m5u_button_set_raw_state(int button, uint32_t msec, bool press);
void m5u_button_set_state(int button, uint32_t msec, int state);
int m5u_button_get_state(int button);
uint32_t m5u_button_last_change(int button);
uint32_t m5u_button_get_debounce_thresh(int button);
uint32_t m5u_button_get_hold_thresh(int button);
uint32_t m5u_button_get_update_msec(int button);

bool m5u_mic_begin(void);
bool m5u_mic_is_enabled(void);
bool m5u_mic_is_recording(void);
void m5u_mic_end(void);
bool m5u_mic_record_i16(int16_t* buffer, size_t samples);
bool m5u_mic_record_i16_at(int16_t* buffer, size_t samples, uint32_t sample_rate_hz);
int m5u_mic_get_noise_filter_level(void);
bool m5u_mic_set_noise_filter_level(int level);

typedef struct {
    int pin_data_in;
    int pin_bck;
    int pin_mck;
    int pin_ws;
    uint32_t sample_rate;
    bool left_channel;
    bool stereo;
    uint8_t over_sampling;
    uint8_t magnification;
    uint8_t noise_filter_level;
    bool use_adc;
    size_t dma_buf_len;
    size_t dma_buf_count;
    uint8_t task_priority;
    uint8_t task_pinned_core;
    int i2s_port;
} m5u_mic_config_t;

bool m5u_mic_get_config(m5u_mic_config_t* out);
void m5u_mic_set_config(const m5u_mic_config_t* config);

typedef struct {
    int pin_data_out;
    int pin_bck;
    int pin_ws;
    uint32_t sample_rate;
    bool stereo;
    bool buzzer;
    bool use_dac;
    uint8_t dac_zero_level;
    uint8_t magnification;
    size_t dma_buf_len;
    size_t dma_buf_count;
    uint8_t task_priority;
    uint8_t task_pinned_core;
    int i2s_port;
} m5u_speaker_config_t;

bool m5u_speaker_begin(void);
bool m5u_speaker_is_enabled(void);
bool m5u_speaker_is_running(void);
void m5u_speaker_end(void);
bool m5u_speaker_get_config(m5u_speaker_config_t* out);
void m5u_speaker_set_config(const m5u_speaker_config_t* config);
void m5u_speaker_set_volume(uint8_t volume);
uint8_t m5u_speaker_get_volume(void);
bool m5u_speaker_tone(uint32_t frequency_hz, uint32_t duration_ms);
bool m5u_speaker_tone_ex(float frequency_hz, uint32_t duration_ms, int channel);
bool m5u_speaker_play_i16(const int16_t* samples, size_t len, uint32_t sample_rate_hz);
bool m5u_speaker_play_u8(const uint8_t* samples, size_t len, uint32_t sample_rate_hz);
bool m5u_speaker_play_wav(const uint8_t* data, size_t len);
bool m5u_speaker_play_i16_ex(const int16_t* samples, size_t len, uint32_t sample_rate_hz, bool stereo, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_play_u8_ex(const uint8_t* samples, size_t len, uint32_t sample_rate_hz, bool stereo, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_play_wav_ex(const uint8_t* data, size_t len, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_is_playing(int channel);
size_t m5u_speaker_get_playing_channels(void);
void m5u_speaker_stop(int channel);
uint8_t m5u_speaker_get_channel_volume(int channel);
void m5u_speaker_set_channel_volume(int channel, uint8_t volume);
void m5u_speaker_set_all_channel_volume(uint8_t volume);

bool m5u_imu_begin(void);
bool m5u_imu_is_enabled(void);
int m5u_imu_get_type(void);
bool m5u_imu_update(void);
bool m5u_imu_get_accel(float* x, float* y, float* z);
bool m5u_imu_get_gyro(float* x, float* y, float* z);
bool m5u_imu_get_mag(float* x, float* y, float* z);
bool m5u_imu_get_temp_c(float* temp);
bool m5u_imu_sleep(void);
bool m5u_imu_load_offset_from_nvs(void);
bool m5u_imu_save_offset_to_nvs(void);
void m5u_imu_clear_offset_data(void);
int32_t m5u_imu_get_offset_data(size_t index);
void m5u_imu_set_offset_data(size_t index, int32_t value);
int16_t m5u_imu_get_raw_data(size_t index);
bool m5u_imu_set_int_pin_active_logic(bool level);
void m5u_imu_set_calibration(uint8_t accel_strength, uint8_t gyro_strength, uint8_t mag_strength);

typedef struct {
    int x;
    int y;
    uint16_t size;
    uint8_t id;
    int prev_x;
    int prev_y;
    int base_x;
    int base_y;
    uint32_t base_msec;
    int state;
    bool is_pressed;
    bool was_pressed;
    bool is_released;
    bool was_released;
    bool was_clicked;
    bool was_hold;
    bool is_holding;
    bool was_flick_start;
    bool is_flicking;
    bool was_flicked;
    bool was_drag_start;
    bool is_dragging;
    bool was_dragged;
    int click_count;
} m5u_touch_detail_t;

typedef struct {
    int x;
    int y;
    uint16_t size;
    uint8_t id;
} m5u_touch_point_t;

#define M5U_CARDPUTER_KEYBOARD_WORD_CAPACITY 32
#define M5U_CARDPUTER_KEYBOARD_HID_CAPACITY 32
#define M5U_CARDPUTER_KEYBOARD_MODIFIER_CAPACITY 8
#define M5U_CARDPUTER_SD_DIR_ENTRY_NAME_CAPACITY 64

typedef struct {
    bool tab;
    bool fn_key;
    bool shift;
    bool ctrl;
    bool opt;
    bool alt;
    bool del;
    bool enter;
    bool space;
    uint8_t modifiers;
    size_t word_len;
    uint8_t word[M5U_CARDPUTER_KEYBOARD_WORD_CAPACITY];
    size_t hid_len;
    uint8_t hid_keys[M5U_CARDPUTER_KEYBOARD_HID_CAPACITY];
    size_t modifier_len;
    uint8_t modifier_keys[M5U_CARDPUTER_KEYBOARD_MODIFIER_CAPACITY];
} m5u_cardputer_keyboard_state_t;

typedef struct {
    uint8_t first;
    uint8_t second;
} m5u_cardputer_key_value_t;

typedef struct {
    char name[M5U_CARDPUTER_SD_DIR_ENTRY_NAME_CAPACITY];
    bool is_directory;
    uint64_t size;
} m5u_cardputer_sd_dir_entry_t;

void m5u_touch_begin(void);
void m5u_touch_update(uint32_t msec);
bool m5u_touch_is_enabled(void);
void m5u_touch_end(void);
int m5u_touch_count(void);
bool m5u_touch_get(int index, int* x, int* y);
bool m5u_touch_get_detail(int index, m5u_touch_detail_t* out);
bool m5u_touch_get_raw(int index, m5u_touch_point_t* out);
void m5u_touch_set_hold_thresh(uint16_t msec);
void m5u_touch_set_flick_thresh(uint16_t distance);
void m5u_set_touch_button_height(uint16_t pixel);
void m5u_set_touch_button_height_by_ratio(uint8_t ratio);
uint16_t m5u_get_touch_button_height(void);

bool m5u_rtc_is_enabled(void);
bool m5u_rtc_begin(void);
bool m5u_rtc_get_volt_low(void);
bool m5u_rtc_get_date(int* year, int* month, int* day, int* weekday);
bool m5u_rtc_get_time(int* hour, int* minute, int* second);
bool m5u_rtc_get_datetime(int* year, int* month, int* day, int* hour, int* minute, int* second);
bool m5u_rtc_set_date(int year, int month, int day, int weekday);
bool m5u_rtc_set_time(int hour, int minute, int second);
bool m5u_rtc_set_datetime(int year, int month, int day, int hour, int minute, int second);
void m5u_rtc_set_system_time_from_rtc(void);
bool m5u_rtc_set_alarm_irq_after(int seconds);
bool m5u_rtc_get_irq_status(void);
void m5u_rtc_clear_irq(void);
void m5u_rtc_disable_irq(void);

int m5u_battery_level(void);
int m5u_battery_voltage_mv(void);
int m5u_battery_current_ma(void);
bool m5u_power_is_charging(void);
int m5u_power_charging_state(void);
bool m5u_power_begin(void);
void m5u_power_set_ext_output(bool enable);
bool m5u_power_get_ext_output(void);
void m5u_power_set_usb_output(bool enable);
bool m5u_power_get_usb_output(void);
void m5u_power_set_led(uint8_t brightness);
void m5u_power_power_off(void);
void m5u_power_timer_sleep(int seconds);
void m5u_power_deep_sleep(uint64_t micro_seconds, bool touch_wakeup);
void m5u_power_light_sleep(uint64_t micro_seconds, bool touch_wakeup);
void m5u_power_set_battery_charge(bool enable);
void m5u_power_set_charge_current(uint16_t max_ma);
void m5u_power_set_charge_voltage(uint16_t max_mv);
uint8_t m5u_power_get_key_state(void);
void m5u_power_set_vibration(uint8_t level);
int m5u_power_get_type(void);
bool m5u_led_begin(void);
bool m5u_led_is_enabled(void);
size_t m5u_led_count(void);
void m5u_led_display(void);
void m5u_led_set_auto_display(bool enable);
void m5u_led_set_brightness(uint8_t brightness);
void m5u_led_set_color(size_t index, uint32_t rgb);
void m5u_led_set_all_color(uint32_t rgb);
bool m5u_power_axp2101_disable_irq(uint64_t mask);
bool m5u_power_axp2101_enable_irq(uint64_t mask);
bool m5u_power_axp2101_clear_irq_statuses(void);
uint64_t m5u_power_axp2101_get_irq_statuses(void);
bool m5u_power_axp2101_is_bat_charger_under_temperature_irq(void);
bool m5u_power_axp2101_is_bat_charger_over_temperature_irq(void);
bool m5u_power_axp2101_is_vbus_insert_irq(void);
bool m5u_power_axp2101_is_vbus_remove_irq(void);

void m5u_log_print(const char* text);
void m5u_log_println(const char* text);
void m5u_log_level(int level, const char* text);
void m5u_log_set_level(int target, int level);
int m5u_log_get_level(int target);
void m5u_log_set_enable_color(int target, bool enable);
bool m5u_log_get_enable_color(int target);
void m5u_log_set_suffix(int target, const char* suffix);
void m5u_set_log_display_index(int index);
bool m5u_sd_begin(void);
void m5u_sd_end(void);
int m5u_sd_card_type(void);
uint64_t m5u_sd_card_size_bytes(void);
uint64_t m5u_sd_total_bytes(void);
uint64_t m5u_sd_used_bytes(void);
bool m5u_sd_exists(const char* path);
uint64_t m5u_sd_file_size(const char* path);
bool m5u_sd_is_directory(const char* path);
size_t m5u_sd_read_file(const char* path, uint8_t* data, size_t len);
size_t m5u_sd_write_file(const char* path, const uint8_t* data, size_t len, bool append);
bool m5u_sd_remove(const char* path);
bool m5u_sd_mkdir(const char* path);
bool m5u_sd_rmdir(const char* path);
bool m5u_sd_rename(const char* from_path, const char* to_path);
size_t m5u_sd_list_dir(const char* path, m5u_cardputer_sd_dir_entry_t* entries, size_t capacity);
bool m5u_i2c_begin(int sda, int scl, uint32_t frequency_hz);
void m5u_i2c_end(void);
bool m5u_i2c_probe(uint8_t address);
bool m5u_i2c_write(uint8_t address, const uint8_t* data, size_t len);
size_t m5u_i2c_read(uint8_t address, uint8_t* data, size_t len);
bool m5u_i2c_write_reg(uint8_t address, uint8_t reg, const uint8_t* data, size_t len);
size_t m5u_i2c_read_reg(uint8_t address, uint8_t reg, uint8_t* data, size_t len);
bool m5u_uart_begin(int rx, int tx, uint32_t baud);
void m5u_uart_end(void);
size_t m5u_uart_available(void);
size_t m5u_uart_read(uint8_t* data, size_t len);
size_t m5u_uart_write(const uint8_t* data, size_t len);
void m5u_uart_flush(void);
bool m5u_gpio_pin_mode(int pin, int mode);
bool m5u_gpio_write(int pin, bool high);
int m5u_gpio_read(int pin);
int m5u_gpio_analog_read(int pin);
int m5u_gpio_analog_read_millivolts(int pin);
bool m5u_gpio_analog_write(int pin, uint8_t duty);
bool m5u_gpio_analog_write_frequency(int pin, uint32_t frequency_hz);
bool m5u_gpio_analog_write_resolution(int pin, uint8_t resolution_bits);
bool m5u_servo_attach(int pin, int channel, int timer, uint32_t frequency_hz, uint16_t min_us, uint16_t max_us);
bool m5u_servo_detach(int channel);
bool m5u_servo_write_pulse_us(int channel, uint16_t pulse_us);

typedef struct {
    bool ready;
    bool moving;
    int16_t yaw_tenths;
    int16_t pitch_tenths;
} m5u_stackchan_motion_status_t;

bool m5u_stackchan_motion_begin(void);
void m5u_stackchan_motion_update(void);
bool m5u_stackchan_motion_move(int16_t yaw_tenths, int16_t pitch_tenths, uint16_t speed_bsp);
bool m5u_stackchan_motion_home(uint16_t speed_bsp);
bool m5u_stackchan_motion_nod(void);
bool m5u_stackchan_motion_shake(void);
bool m5u_stackchan_motion_status(m5u_stackchan_motion_status_t* out);
bool m5u_spi_begin(int sck, int miso, int mosi, int cs);
void m5u_spi_end(void);
uint8_t m5u_spi_transfer_byte(uint8_t value, uint32_t frequency_hz, uint8_t mode, bool lsb_first);
bool m5u_spi_transfer(const uint8_t* tx, uint8_t* rx, size_t len, uint32_t frequency_hz, uint8_t mode, bool lsb_first);
bool m5u_spi_write(const uint8_t* data, size_t len, uint32_t frequency_hz, uint8_t mode, bool lsb_first);

bool m5u_cardputer_begin(bool enable_keyboard);
bool m5u_cardputer_begin_with_config(const m5u_config_t* config, bool enable_keyboard);
void m5u_cardputer_update(void);
void m5u_cardputer_keyboard_begin(void);
bool m5u_cardputer_keyboard_is_pressed(void);
uint8_t m5u_cardputer_keyboard_pressed_count(void);
bool m5u_cardputer_keyboard_is_change(void);
bool m5u_cardputer_keyboard_is_key_pressed(uint8_t key);
uint8_t m5u_cardputer_keyboard_get_key(uint8_t x, uint8_t y);
bool m5u_cardputer_keyboard_get_key_value(uint8_t x, uint8_t y, m5u_cardputer_key_value_t* out);
bool m5u_cardputer_keyboard_get_state(m5u_cardputer_keyboard_state_t* out);
bool m5u_cardputer_keyboard_capslocked(void);
void m5u_cardputer_keyboard_set_capslocked(bool locked);
bool m5u_cardputer_sd_begin(int sck, int miso, int mosi, int cs, uint32_t frequency_hz);
void m5u_cardputer_sd_end(void);
int m5u_cardputer_sd_card_type(void);
uint64_t m5u_cardputer_sd_card_size_bytes(void);
uint64_t m5u_cardputer_sd_total_bytes(void);
uint64_t m5u_cardputer_sd_used_bytes(void);
bool m5u_cardputer_sd_exists(const char* path);
uint64_t m5u_cardputer_sd_file_size(const char* path);
bool m5u_cardputer_sd_is_directory(const char* path);
size_t m5u_cardputer_sd_list_dir(const char* path, m5u_cardputer_sd_dir_entry_t* entries, size_t capacity);
size_t m5u_cardputer_sd_read_file(const char* path, uint8_t* data, size_t len);
size_t m5u_cardputer_sd_write_file(const char* path, const uint8_t* data, size_t len, bool append);
bool m5u_cardputer_sd_remove(const char* path);
bool m5u_cardputer_sd_mkdir(const char* path);
bool m5u_cardputer_sd_rmdir(const char* path);
bool m5u_cardputer_sd_rename(const char* from_path, const char* to_path);
bool m5u_cardputer_ir_begin(int pin);
bool m5u_cardputer_ir_send_nec(uint16_t address, uint8_t command, uint8_t repeats);
bool m5u_cardputer_grove_i2c_begin(int sda, int scl, uint32_t frequency_hz);
void m5u_cardputer_grove_i2c_end(void);
bool m5u_cardputer_grove_i2c_probe(uint8_t address);
bool m5u_cardputer_grove_i2c_write(uint8_t address, const uint8_t* data, size_t len);
size_t m5u_cardputer_grove_i2c_read(uint8_t address, uint8_t* data, size_t len);
bool m5u_cardputer_grove_i2c_write_reg(uint8_t address, uint8_t reg, const uint8_t* data, size_t len);
size_t m5u_cardputer_grove_i2c_read_reg(uint8_t address, uint8_t reg, uint8_t* data, size_t len);
bool m5u_cardputer_grove_gpio_pin_mode(int pin, int mode);
bool m5u_cardputer_grove_gpio_write(int pin, bool high);
int m5u_cardputer_grove_gpio_read(int pin);
bool m5u_cardputer_grove_uart_begin(int rx, int tx, uint32_t baud);
void m5u_cardputer_grove_uart_end(void);
size_t m5u_cardputer_grove_uart_available(void);
size_t m5u_cardputer_grove_uart_read(uint8_t* data, size_t len);
size_t m5u_cardputer_grove_uart_write(const uint8_t* data, size_t len);
void m5u_cardputer_grove_uart_flush(void);

#ifdef __cplusplus
}
#endif
